blank_issues_enabled: false
contact_links:
  - name: "Need help or want to report an issue?"
    url: "https://github.com/BayBreezy/ui-thing/issues/new/choose"
    about: "Use one of our templates to help us address your feedback faster!"
  - name: GitHub Community Support
    url: https://github.com/BayBreezy/ui-thing/discussions
    about: Please ask and answer questions here.
