blank_issues_enabled: false
contact_links:
  - name: ðŸ’­ Discussions
    url: https://github.com/BayBreezy/ui-thing/discussions
    about: "Ask questions, share ideas, and connect with the community."
  - name: ðŸ’Œ Contact Me
    url: mailto:behon.baker@yahoo.com
    about: "Get in touch with me directly."
